apiVersion: apps/v1
kind: Deployment
metadata:
  name: james-k8s-deployment
  labels:
    app: jamesk8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jamesk8s
  template:
    metadata:
      labels:
        app: jamesk8s
    spec:
      containers:
      - name: jamesk8s
        image: "gcr.io/james-app-dev/k8snodeapi:latest"
        env:
        - name: "PORT"
          value: "8081"