kind: Service
apiVersion: v1
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
    type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    # nodePort : 8081
    targetPort: 8080