kind: Service
apiVersion: v1
metadata:
  name: james-k8s-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: jamesk8s
  ports:
  - protocol: TCP
    port: 80
    # nodePort : 8081
    targetPort: 8081
  